version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
      - "15692:15692"  # Prometheus metrics port (new in RabbitMQ 4)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      # Enable new RabbitMQ 4 features
      RABBITMQ_FEATURE_FLAGS: all
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    build: .
    container_name: rabbitmq-patterns-app
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq-network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  rabbitmq-network:
    driver: bridge